// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID           int64
	SpuCode      string
	Name         string
	Description  string
	Price        pgtype.Numeric
	Status       string
	MainMediaKey string
	Quantity     int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    pgtype.Timestamptz
}
