// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountProducts = `-- name: CountProducts :one
SELECT count(*)
FROM products
WHERE deleted_at IS NULL
  AND ($1::TEXT IS NULL OR status = $1::TEXT)
`

// CountProducts
//
//	SELECT count(*)
//	FROM products
//	WHERE deleted_at IS NULL
//	  AND ($1::TEXT IS NULL OR status = $1::TEXT)
func (q *Queries) CountProducts(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, CountProducts, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateProduct = `-- name: CreateProduct :one
INSERT INTO products (spu_code, name, description, price, status, main_media_key, quantity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	SpuCode      string
	Name         string
	Description  string
	Price        pgtype.Numeric
	Status       string
	MainMediaKey string
	Quantity     int64
}

// CreateProduct
//
//	INSERT INTO products (spu_code, name, description, price, status, main_media_key, quantity)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, CreateProduct,
		arg.SpuCode,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Status,
		arg.MainMediaKey,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SpuCode,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.MainMediaKey,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetProduct = `-- name: GetProduct :one

SELECT id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
FROM products
WHERE id = $1
  AND deleted_at IS NULL
`

// sqlc 的 queries 目录:每条查询上方的 -- name: 注释决定生成的方法名与返回形态。
//
//	:one   返回单行,无结果时返回 pgx.ErrNoRows
//	:many  返回多行
//	:exec  不返回行
//	:execrows 返回受影响行数(用于判断 UPDATE/DELETE 是否命中)
//
// 这是随模板附带的示例,对应 schema/0001_products.sql。
// co new 默认会连同示例资源一起删掉(--keep-example 可保留)。
//
//	SELECT id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
//	FROM products
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, GetProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SpuCode,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.MainMediaKey,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetProductBySpuCode = `-- name: GetProductBySpuCode :one
SELECT id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
FROM products
WHERE spu_code = $1
  AND deleted_at IS NULL
`

// GetProductBySpuCode
//
//	SELECT id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
//	FROM products
//	WHERE spu_code = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetProductBySpuCode(ctx context.Context, spuCode string) (Product, error) {
	row := q.db.QueryRow(ctx, GetProductBySpuCode, spuCode)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SpuCode,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.MainMediaKey,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ListProducts = `-- name: ListProducts :many
SELECT id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
FROM products
WHERE deleted_at IS NULL
  AND ($1::TEXT IS NULL OR status = $1::TEXT)
  AND ($2::TIMESTAMPTZ IS NULL
    OR (created_at, id) < ($2::TIMESTAMPTZ, $3::BIGINT))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListProductsParams struct {
	Status          *string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        *int64
	PageSize        int32
}

// 用 keyset 分页而不是 OFFSET:OFFSET 需要扫过并丢弃前面所有行,
// 翻到深页时会线性变慢。这里以 (created_at, id) 为游标。
//
//	SELECT id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
//	FROM products
//	WHERE deleted_at IS NULL
//	  AND ($1::TEXT IS NULL OR status = $1::TEXT)
//	  AND ($2::TIMESTAMPTZ IS NULL
//	    OR (created_at, id) < ($2::TIMESTAMPTZ, $3::BIGINT))
//	ORDER BY created_at DESC, id DESC
//	LIMIT $4
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, ListProducts,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SpuCode,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Status,
			&i.MainMediaKey,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE products
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// 返回 execrows 而非 exec:调用方据此区分「删掉了」和「本来就不存在」
//
//	UPDATE products
//	SET deleted_at = now(),
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteProduct(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, SoftDeleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const UpdateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name           = COALESCE($1, name),
    description    = COALESCE($2, description),
    price          = COALESCE($3, price),
    status         = COALESCE($4, status),
    main_media_key = COALESCE($5, main_media_key),
    quantity       = COALESCE($6, quantity),
    updated_at     = now()
WHERE id = $7
  AND deleted_at IS NULL
RETURNING id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	Name         *string
	Description  *string
	Price        pgtype.Numeric
	Status       *string
	MainMediaKey *string
	Quantity     *int64
	ID           int64
}

// COALESCE + narg 实现部分更新:传 NULL 的字段保持原值,
// 免得为每种字段组合各写一条 UPDATE
//
//	UPDATE products
//	SET name           = COALESCE($1, name),
//	    description    = COALESCE($2, description),
//	    price          = COALESCE($3, price),
//	    status         = COALESCE($4, status),
//	    main_media_key = COALESCE($5, main_media_key),
//	    quantity       = COALESCE($6, quantity),
//	    updated_at     = now()
//	WHERE id = $7
//	  AND deleted_at IS NULL
//	RETURNING id, spu_code, name, description, price, status, main_media_key, quantity, created_at, updated_at, deleted_at
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, UpdateProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Status,
		arg.MainMediaKey,
		arg.Quantity,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SpuCode,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Status,
		&i.MainMediaKey,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
