services:

  ecommerce-search:
    image: harbor.apikv.com:5443/ecommerce/search:dev
    networks:
      - ecommerce
    ports:
      - "0.0.0.0:30002:30002"
    environment:
      - RUN_MODE=prod
      - CONFIG_CENTER=http://apikv.com:8500
      - CONFIG_PATH=ecommerce/search/dev.yml
    container_name: ecommerce-search
    restart: on-failure:3

networks:
  ecommerce:
    external: true
