// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/search/v1/search.proto (package search.v1, syntax proto3)
/* eslint-disable */

// 独立搜索功能

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/search/v1/search.proto.
 */
export const file_api_search_v1_search: GenFile = /*@__PURE__*/
  fileDesc("ChphcGkvc2VhcmNoL3YxL3NlYXJjaC5wcm90bxIJc2VhcmNoLnYxIiwKDVNlYXJjaFJlcXVlc3QSDQoFaW5kZXgYASABKAkSDAoEbmFtZRgCIAEoCSI2Cg5TZWFyY2hSZXNwb25zZRIkCghwcm9kdWN0cxgBIAMoCzISLnNlYXJjaC52MS5Qcm9kdWN0In4KB1Byb2R1Y3QSCgoCaWQYASABKA0SEAoIc3B1X2NvZGUYAiABKAkSDQoFcHJpY2UYAyABKAESDgoGc3RhdHVzGAQgASgJEhYKDm1haW5fbWVkaWFfdXJsGAUgASgJEhAKCHF1YW50aXR5GAYgASgNEgwKBG5hbWUYByABKAkyUAoNU2VhcmNoU2VydmljZRI/CgZTZWFyY2gSGC5zZWFyY2gudjEuU2VhcmNoUmVxdWVzdBoZLnNlYXJjaC52MS5TZWFyY2hSZXNwb25zZSIAQqABCg1jb20uc2VhcmNoLnYxQgtTZWFyY2hQcm90b1ABWj1naXRodWIuY29tL2xlbnMwNzcvZ28tY29ubmVjdC10ZW1wbGF0ZS9hcGkvc2VhcmNoL3YxO3NlYXJjaHYxogIDU1hYqgIJU2VhcmNoLlYxygIJU2VhcmNoXFYx4gIVU2VhcmNoXFYxXEdQQk1ldGFkYXRh6gIKU2VhcmNoOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message search.v1.SearchRequest
 */
export type SearchRequest = Message<"search.v1.SearchRequest"> & {
  /**
   * @generated from field: string index = 1;
   */
  index: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message search.v1.SearchRequest.
 * Use `create(SearchRequestSchema)` to create a new message.
 */
export const SearchRequestSchema: GenMessage<SearchRequest> = /*@__PURE__*/
  messageDesc(file_api_search_v1_search, 0);

/**
 * @generated from message search.v1.SearchResponse
 */
export type SearchResponse = Message<"search.v1.SearchResponse"> & {
  /**
   * @generated from field: repeated search.v1.Product products = 1;
   */
  products: Product[];
};

/**
 * Describes the message search.v1.SearchResponse.
 * Use `create(SearchResponseSchema)` to create a new message.
 */
export const SearchResponseSchema: GenMessage<SearchResponse> = /*@__PURE__*/
  messageDesc(file_api_search_v1_search, 1);

/**
 * 定义 Product 消息 (对应 Go 结构体中的 Product)
 *
 * @generated from message search.v1.Product
 */
export type Product = Message<"search.v1.Product"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string spu_code = 2;
   */
  spuCode: string;

  /**
   * @generated from field: double price = 3;
   */
  price: number;

  /**
   * @generated from field: string status = 4;
   */
  status: string;

  /**
   * @generated from field: string main_media_url = 5;
   */
  mainMediaUrl: string;

  /**
   * @generated from field: uint32 quantity = 6;
   */
  quantity: number;

  /**
   * @generated from field: string name = 7;
   */
  name: string;
};

/**
 * Describes the message search.v1.Product.
 * Use `create(ProductSchema)` to create a new message.
 */
export const ProductSchema: GenMessage<Product> = /*@__PURE__*/
  messageDesc(file_api_search_v1_search, 2);

/**
 * @generated from service search.v1.SearchService
 */
export const SearchService: GenService<{
  /**
   * @generated from rpc search.v1.SearchService.Search
   */
  search: {
    methodKind: "unary";
    input: typeof SearchRequestSchema;
    output: typeof SearchResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_search_v1_search, 0);

