// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/search/v1/search.proto

// 独立搜索功能

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *SearchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// 定义 Product 消息 (对应 Go 结构体中的 Product)
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpuCode       string                 `protobuf:"bytes,2,opt,name=spu_code,json=spuCode,proto3" json:"spu_code,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	MainMediaUrl  string                 `protobuf:"bytes,5,opt,name=main_media_url,json=mainMediaUrl,proto3" json:"main_media_url,omitempty"`
	Quantity      uint32                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetSpuCode() string {
	if x != nil {
		return x.SpuCode
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Product) GetMainMediaUrl() string {
	if x != nil {
		return x.MainMediaUrl
	}
	return ""
}

func (x *Product) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_search_v1_search_proto protoreflect.FileDescriptor

const file_api_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/search/v1/search.proto\x12\tsearch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x0eSearchResponse\x12.\n" +
	"\bproducts\x18\x01 \x03(\v2\x12.search.v1.ProductR\bproducts\"\xb8\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bspu_code\x18\x02 \x01(\tR\aspuCode\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12$\n" +
	"\x0emain_media_url\x18\x05 \x01(\tR\fmainMediaUrl\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\rR\bquantity\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name2P\n" +
	"\rSearchService\x12?\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponse\"\x00B\xa0\x01\n" +
	"\rcom.search.v1B\vSearchProtoP\x01Z=github.com/lens077/go-connect-template/api/search/v1;searchv1\xa2\x02\x03SXX\xaa\x02\tSearch.V1\xca\x02\tSearch\\V1\xe2\x02\x15Search\\V1\\GPBMetadata\xea\x02\n" +
	"Search::V1b\x06proto3"

var (
	file_api_search_v1_search_proto_rawDescOnce sync.Once
	file_api_search_v1_search_proto_rawDescData []byte
)

func file_api_search_v1_search_proto_rawDescGZIP() []byte {
	file_api_search_v1_search_proto_rawDescOnce.Do(func() {
		file_api_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_search_v1_search_proto_rawDesc), len(file_api_search_v1_search_proto_rawDesc)))
	})
	return file_api_search_v1_search_proto_rawDescData
}

var file_api_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_search_v1_search_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: search.v1.SearchRequest
	(*SearchResponse)(nil), // 1: search.v1.SearchResponse
	(*Product)(nil),        // 2: search.v1.Product
}
var file_api_search_v1_search_proto_depIdxs = []int32{
	2, // 0: search.v1.SearchResponse.products:type_name -> search.v1.Product
	0, // 1: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	1, // 2: search.v1.SearchService.Search:output_type -> search.v1.SearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_search_v1_search_proto_init() }
func file_api_search_v1_search_proto_init() {
	if File_api_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_search_v1_search_proto_rawDesc), len(file_api_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_search_v1_search_proto_goTypes,
		DependencyIndexes: file_api_search_v1_search_proto_depIdxs,
		MessageInfos:      file_api_search_v1_search_proto_msgTypes,
	}.Build()
	File_api_search_v1_search_proto = out.File
	file_api_search_v1_search_proto_goTypes = nil
	file_api_search_v1_search_proto_depIdxs = nil
}
