// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/config/v1/config.proto

package configv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lens077/go-connect-template/api/config/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "config.v1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServiceListNamespacesProcedure is the fully-qualified name of the ConfigService's
	// ListNamespaces RPC.
	ConfigServiceListNamespacesProcedure = "/config.v1.ConfigService/ListNamespaces"
	// ConfigServiceListKeysProcedure is the fully-qualified name of the ConfigService's ListKeys RPC.
	ConfigServiceListKeysProcedure = "/config.v1.ConfigService/ListKeys"
	// ConfigServiceGetKeyProcedure is the fully-qualified name of the ConfigService's GetKey RPC.
	ConfigServiceGetKeyProcedure = "/config.v1.ConfigService/GetKey"
	// ConfigServicePutKeyProcedure is the fully-qualified name of the ConfigService's PutKey RPC.
	ConfigServicePutKeyProcedure = "/config.v1.ConfigService/PutKey"
	// ConfigServiceDeleteKeyProcedure is the fully-qualified name of the ConfigService's DeleteKey RPC.
	ConfigServiceDeleteKeyProcedure = "/config.v1.ConfigService/DeleteKey"
	// ConfigServiceListRevisionsProcedure is the fully-qualified name of the ConfigService's
	// ListRevisions RPC.
	ConfigServiceListRevisionsProcedure = "/config.v1.ConfigService/ListRevisions"
	// ConfigServiceGetRevisionProcedure is the fully-qualified name of the ConfigService's GetRevision
	// RPC.
	ConfigServiceGetRevisionProcedure = "/config.v1.ConfigService/GetRevision"
	// ConfigServiceRollbackProcedure is the fully-qualified name of the ConfigService's Rollback RPC.
	ConfigServiceRollbackProcedure = "/config.v1.ConfigService/Rollback"
	// ConfigServiceWatchKeysProcedure is the fully-qualified name of the ConfigService's WatchKeys RPC.
	ConfigServiceWatchKeysProcedure = "/config.v1.ConfigService/WatchKeys"
)

// ConfigServiceClient is a client for the config.v1.ConfigService service.
type ConfigServiceClient interface {
	// 列出配置中心已有的 namespace 及其下已有配置的 environment,供前端下拉选择(免手输)。
	ListNamespaces(context.Context, *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error)
	// 列出某 namespace+environment 下(可按前缀过滤)的 key 元数据,不返回大 value。
	ListKeys(context.Context, *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.ListKeysResponse], error)
	// 取单个 key 的当前值。
	GetKey(context.Context, *connect.Request[v1.GetKeyRequest]) (*connect.Response[v1.GetKeyResponse], error)
	// 创建或更新 key,产生一条新的版本记录;服务端按 format 校验语法。
	PutKey(context.Context, *connect.Request[v1.PutKeyRequest]) (*connect.Response[v1.PutKeyResponse], error)
	// 删除 key(连同其历史)。
	DeleteKey(context.Context, *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error)
	// 列出某 key 的版本历史。
	ListRevisions(context.Context, *connect.Request[v1.ListRevisionsRequest]) (*connect.Response[v1.ListRevisionsResponse], error)
	// 取某个历史版本的值。
	GetRevision(context.Context, *connect.Request[v1.GetRevisionRequest]) (*connect.Response[v1.GetRevisionResponse], error)
	// 回滚:用指定历史版本的值写为新版本。
	Rollback(context.Context, *connect.Request[v1.RollbackRequest]) (*connect.Response[v1.RollbackResponse], error)
	// 订阅配置变更(服务端流)。建流时先推一遍当前值(SNAPSHOT),之后推增量。
	// 断线重连会重新收到 SNAPSHOT —— 断连期间漏掉的变更由此自愈,客户端无需自己补偿。
	WatchKeys(context.Context, *connect.Request[v1.WatchKeysRequest]) (*connect.ServerStreamForClient[v1.WatchKeysResponse], error)
}

// NewConfigServiceClient constructs a client for the config.v1.ConfigService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := v1.File_api_config_v1_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		listNamespaces: connect.NewClient[v1.ListNamespacesRequest, v1.ListNamespacesResponse](
			httpClient,
			baseURL+ConfigServiceListNamespacesProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListNamespaces")),
			connect.WithClientOptions(opts...),
		),
		listKeys: connect.NewClient[v1.ListKeysRequest, v1.ListKeysResponse](
			httpClient,
			baseURL+ConfigServiceListKeysProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListKeys")),
			connect.WithClientOptions(opts...),
		),
		getKey: connect.NewClient[v1.GetKeyRequest, v1.GetKeyResponse](
			httpClient,
			baseURL+ConfigServiceGetKeyProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetKey")),
			connect.WithClientOptions(opts...),
		),
		putKey: connect.NewClient[v1.PutKeyRequest, v1.PutKeyResponse](
			httpClient,
			baseURL+ConfigServicePutKeyProcedure,
			connect.WithSchema(configServiceMethods.ByName("PutKey")),
			connect.WithClientOptions(opts...),
		),
		deleteKey: connect.NewClient[v1.DeleteKeyRequest, v1.DeleteKeyResponse](
			httpClient,
			baseURL+ConfigServiceDeleteKeyProcedure,
			connect.WithSchema(configServiceMethods.ByName("DeleteKey")),
			connect.WithClientOptions(opts...),
		),
		listRevisions: connect.NewClient[v1.ListRevisionsRequest, v1.ListRevisionsResponse](
			httpClient,
			baseURL+ConfigServiceListRevisionsProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListRevisions")),
			connect.WithClientOptions(opts...),
		),
		getRevision: connect.NewClient[v1.GetRevisionRequest, v1.GetRevisionResponse](
			httpClient,
			baseURL+ConfigServiceGetRevisionProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetRevision")),
			connect.WithClientOptions(opts...),
		),
		rollback: connect.NewClient[v1.RollbackRequest, v1.RollbackResponse](
			httpClient,
			baseURL+ConfigServiceRollbackProcedure,
			connect.WithSchema(configServiceMethods.ByName("Rollback")),
			connect.WithClientOptions(opts...),
		),
		watchKeys: connect.NewClient[v1.WatchKeysRequest, v1.WatchKeysResponse](
			httpClient,
			baseURL+ConfigServiceWatchKeysProcedure,
			connect.WithSchema(configServiceMethods.ByName("WatchKeys")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	listNamespaces *connect.Client[v1.ListNamespacesRequest, v1.ListNamespacesResponse]
	listKeys       *connect.Client[v1.ListKeysRequest, v1.ListKeysResponse]
	getKey         *connect.Client[v1.GetKeyRequest, v1.GetKeyResponse]
	putKey         *connect.Client[v1.PutKeyRequest, v1.PutKeyResponse]
	deleteKey      *connect.Client[v1.DeleteKeyRequest, v1.DeleteKeyResponse]
	listRevisions  *connect.Client[v1.ListRevisionsRequest, v1.ListRevisionsResponse]
	getRevision    *connect.Client[v1.GetRevisionRequest, v1.GetRevisionResponse]
	rollback       *connect.Client[v1.RollbackRequest, v1.RollbackResponse]
	watchKeys      *connect.Client[v1.WatchKeysRequest, v1.WatchKeysResponse]
}

// ListNamespaces calls config.v1.ConfigService.ListNamespaces.
func (c *configServiceClient) ListNamespaces(ctx context.Context, req *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error) {
	return c.listNamespaces.CallUnary(ctx, req)
}

// ListKeys calls config.v1.ConfigService.ListKeys.
func (c *configServiceClient) ListKeys(ctx context.Context, req *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.ListKeysResponse], error) {
	return c.listKeys.CallUnary(ctx, req)
}

// GetKey calls config.v1.ConfigService.GetKey.
func (c *configServiceClient) GetKey(ctx context.Context, req *connect.Request[v1.GetKeyRequest]) (*connect.Response[v1.GetKeyResponse], error) {
	return c.getKey.CallUnary(ctx, req)
}

// PutKey calls config.v1.ConfigService.PutKey.
func (c *configServiceClient) PutKey(ctx context.Context, req *connect.Request[v1.PutKeyRequest]) (*connect.Response[v1.PutKeyResponse], error) {
	return c.putKey.CallUnary(ctx, req)
}

// DeleteKey calls config.v1.ConfigService.DeleteKey.
func (c *configServiceClient) DeleteKey(ctx context.Context, req *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error) {
	return c.deleteKey.CallUnary(ctx, req)
}

// ListRevisions calls config.v1.ConfigService.ListRevisions.
func (c *configServiceClient) ListRevisions(ctx context.Context, req *connect.Request[v1.ListRevisionsRequest]) (*connect.Response[v1.ListRevisionsResponse], error) {
	return c.listRevisions.CallUnary(ctx, req)
}

// GetRevision calls config.v1.ConfigService.GetRevision.
func (c *configServiceClient) GetRevision(ctx context.Context, req *connect.Request[v1.GetRevisionRequest]) (*connect.Response[v1.GetRevisionResponse], error) {
	return c.getRevision.CallUnary(ctx, req)
}

// Rollback calls config.v1.ConfigService.Rollback.
func (c *configServiceClient) Rollback(ctx context.Context, req *connect.Request[v1.RollbackRequest]) (*connect.Response[v1.RollbackResponse], error) {
	return c.rollback.CallUnary(ctx, req)
}

// WatchKeys calls config.v1.ConfigService.WatchKeys.
func (c *configServiceClient) WatchKeys(ctx context.Context, req *connect.Request[v1.WatchKeysRequest]) (*connect.ServerStreamForClient[v1.WatchKeysResponse], error) {
	return c.watchKeys.CallServerStream(ctx, req)
}

// ConfigServiceHandler is an implementation of the config.v1.ConfigService service.
type ConfigServiceHandler interface {
	// 列出配置中心已有的 namespace 及其下已有配置的 environment,供前端下拉选择(免手输)。
	ListNamespaces(context.Context, *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error)
	// 列出某 namespace+environment 下(可按前缀过滤)的 key 元数据,不返回大 value。
	ListKeys(context.Context, *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.ListKeysResponse], error)
	// 取单个 key 的当前值。
	GetKey(context.Context, *connect.Request[v1.GetKeyRequest]) (*connect.Response[v1.GetKeyResponse], error)
	// 创建或更新 key,产生一条新的版本记录;服务端按 format 校验语法。
	PutKey(context.Context, *connect.Request[v1.PutKeyRequest]) (*connect.Response[v1.PutKeyResponse], error)
	// 删除 key(连同其历史)。
	DeleteKey(context.Context, *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error)
	// 列出某 key 的版本历史。
	ListRevisions(context.Context, *connect.Request[v1.ListRevisionsRequest]) (*connect.Response[v1.ListRevisionsResponse], error)
	// 取某个历史版本的值。
	GetRevision(context.Context, *connect.Request[v1.GetRevisionRequest]) (*connect.Response[v1.GetRevisionResponse], error)
	// 回滚:用指定历史版本的值写为新版本。
	Rollback(context.Context, *connect.Request[v1.RollbackRequest]) (*connect.Response[v1.RollbackResponse], error)
	// 订阅配置变更(服务端流)。建流时先推一遍当前值(SNAPSHOT),之后推增量。
	// 断线重连会重新收到 SNAPSHOT —— 断连期间漏掉的变更由此自愈,客户端无需自己补偿。
	WatchKeys(context.Context, *connect.Request[v1.WatchKeysRequest], *connect.ServerStream[v1.WatchKeysResponse]) error
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := v1.File_api_config_v1_config_proto.Services().ByName("ConfigService").Methods()
	configServiceListNamespacesHandler := connect.NewUnaryHandler(
		ConfigServiceListNamespacesProcedure,
		svc.ListNamespaces,
		connect.WithSchema(configServiceMethods.ByName("ListNamespaces")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceListKeysHandler := connect.NewUnaryHandler(
		ConfigServiceListKeysProcedure,
		svc.ListKeys,
		connect.WithSchema(configServiceMethods.ByName("ListKeys")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetKeyHandler := connect.NewUnaryHandler(
		ConfigServiceGetKeyProcedure,
		svc.GetKey,
		connect.WithSchema(configServiceMethods.ByName("GetKey")),
		connect.WithHandlerOptions(opts...),
	)
	configServicePutKeyHandler := connect.NewUnaryHandler(
		ConfigServicePutKeyProcedure,
		svc.PutKey,
		connect.WithSchema(configServiceMethods.ByName("PutKey")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceDeleteKeyHandler := connect.NewUnaryHandler(
		ConfigServiceDeleteKeyProcedure,
		svc.DeleteKey,
		connect.WithSchema(configServiceMethods.ByName("DeleteKey")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceListRevisionsHandler := connect.NewUnaryHandler(
		ConfigServiceListRevisionsProcedure,
		svc.ListRevisions,
		connect.WithSchema(configServiceMethods.ByName("ListRevisions")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetRevisionHandler := connect.NewUnaryHandler(
		ConfigServiceGetRevisionProcedure,
		svc.GetRevision,
		connect.WithSchema(configServiceMethods.ByName("GetRevision")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceRollbackHandler := connect.NewUnaryHandler(
		ConfigServiceRollbackProcedure,
		svc.Rollback,
		connect.WithSchema(configServiceMethods.ByName("Rollback")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceWatchKeysHandler := connect.NewServerStreamHandler(
		ConfigServiceWatchKeysProcedure,
		svc.WatchKeys,
		connect.WithSchema(configServiceMethods.ByName("WatchKeys")),
		connect.WithHandlerOptions(opts...),
	)
	return "/config.v1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServiceListNamespacesProcedure:
			configServiceListNamespacesHandler.ServeHTTP(w, r)
		case ConfigServiceListKeysProcedure:
			configServiceListKeysHandler.ServeHTTP(w, r)
		case ConfigServiceGetKeyProcedure:
			configServiceGetKeyHandler.ServeHTTP(w, r)
		case ConfigServicePutKeyProcedure:
			configServicePutKeyHandler.ServeHTTP(w, r)
		case ConfigServiceDeleteKeyProcedure:
			configServiceDeleteKeyHandler.ServeHTTP(w, r)
		case ConfigServiceListRevisionsProcedure:
			configServiceListRevisionsHandler.ServeHTTP(w, r)
		case ConfigServiceGetRevisionProcedure:
			configServiceGetRevisionHandler.ServeHTTP(w, r)
		case ConfigServiceRollbackProcedure:
			configServiceRollbackHandler.ServeHTTP(w, r)
		case ConfigServiceWatchKeysProcedure:
			configServiceWatchKeysHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) ListNamespaces(context.Context, *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1.ConfigService.ListNamespaces is not implemented"))
}

func (UnimplementedConfigServiceHandler) ListKeys(context.Context, *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.ListKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1.ConfigService.ListKeys is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetKey(context.Context, *connect.Request[v1.GetKeyRequest]) (*connect.Response[v1.GetKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1.ConfigService.GetKey is not implemented"))
}

func (UnimplementedConfigServiceHandler) PutKey(context.Context, *connect.Request[v1.PutKeyRequest]) (*connect.Response[v1.PutKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1.ConfigService.PutKey is not implemented"))
}

func (UnimplementedConfigServiceHandler) DeleteKey(context.Context, *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1.ConfigService.DeleteKey is not implemented"))
}

func (UnimplementedConfigServiceHandler) ListRevisions(context.Context, *connect.Request[v1.ListRevisionsRequest]) (*connect.Response[v1.ListRevisionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1.ConfigService.ListRevisions is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetRevision(context.Context, *connect.Request[v1.GetRevisionRequest]) (*connect.Response[v1.GetRevisionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1.ConfigService.GetRevision is not implemented"))
}

func (UnimplementedConfigServiceHandler) Rollback(context.Context, *connect.Request[v1.RollbackRequest]) (*connect.Response[v1.RollbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("config.v1.ConfigService.Rollback is not implemented"))
}

func (UnimplementedConfigServiceHandler) WatchKeys(context.Context, *connect.Request[v1.WatchKeysRequest], *connect.ServerStream[v1.WatchKeysResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("config.v1.ConfigService.WatchKeys is not implemented"))
}
