apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      name: example
      labels:
        app: example
    spec:
      containers:
        - name: example
          image: example/example:dev
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: org-service-v1
            - name: CONSUL_ENABLED
              value: "true"
            - name: CONSUL_ADDR
              value: "consul.example.com:8501"
            - name: CONSUL_PATH
              value: "org/example/prod.yml"
            - name: CONSUL_SCHEME
              value: "https"
            - name: CONSUL_INSECURE_SKIP_VERIFY
              value: "true"
          ports:
            - containerPort: 30002
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
#          envFrom:
#            - configMapRef:
#                name: example-config
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 30002
#            initialDelaySeconds: 20
#            periodSeconds: 10
#            failureThreshold: 3
#          readinessProbe:
#            httpGet:
#              path: /healthz
#              port: 30002

      restartPolicy: Always
      
