// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/config/v1/config.proto

package configv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 配置内容格式
type ConfigFormat int32

const (
	ConfigFormat_CONFIG_FORMAT_UNSPECIFIED ConfigFormat = 0
	ConfigFormat_CONFIG_FORMAT_YAML        ConfigFormat = 1
	ConfigFormat_CONFIG_FORMAT_TOML        ConfigFormat = 2
	ConfigFormat_CONFIG_FORMAT_JSON        ConfigFormat = 3
	ConfigFormat_CONFIG_FORMAT_PLAINTEXT   ConfigFormat = 4
)

// Enum value maps for ConfigFormat.
var (
	ConfigFormat_name = map[int32]string{
		0: "CONFIG_FORMAT_UNSPECIFIED",
		1: "CONFIG_FORMAT_YAML",
		2: "CONFIG_FORMAT_TOML",
		3: "CONFIG_FORMAT_JSON",
		4: "CONFIG_FORMAT_PLAINTEXT",
	}
	ConfigFormat_value = map[string]int32{
		"CONFIG_FORMAT_UNSPECIFIED": 0,
		"CONFIG_FORMAT_YAML":        1,
		"CONFIG_FORMAT_TOML":        2,
		"CONFIG_FORMAT_JSON":        3,
		"CONFIG_FORMAT_PLAINTEXT":   4,
	}
)

func (x ConfigFormat) Enum() *ConfigFormat {
	p := new(ConfigFormat)
	*p = x
	return p
}

func (x ConfigFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_api_config_v1_config_proto_enumTypes[0].Descriptor()
}

func (ConfigFormat) Type() protoreflect.EnumType {
	return &file_api_config_v1_config_proto_enumTypes[0]
}

func (x ConfigFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigFormat.Descriptor instead.
func (ConfigFormat) EnumDescriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{0}
}

// 变更事件类型
type WatchEventType int32

const (
	WatchEventType_WATCH_EVENT_TYPE_UNSPECIFIED WatchEventType = 0
	WatchEventType_WATCH_EVENT_TYPE_SNAPSHOT    WatchEventType = 1 // 建流时推送的当前值
	WatchEventType_WATCH_EVENT_TYPE_PUT         WatchEventType = 2 // 新增/更新/回滚
	WatchEventType_WATCH_EVENT_TYPE_DELETE      WatchEventType = 3 // 删除,entry 仅含 namespace/environment/key
	WatchEventType_WATCH_EVENT_TYPE_HEARTBEAT   WatchEventType = 4 // 保活,entry 为空
)

// Enum value maps for WatchEventType.
var (
	WatchEventType_name = map[int32]string{
		0: "WATCH_EVENT_TYPE_UNSPECIFIED",
		1: "WATCH_EVENT_TYPE_SNAPSHOT",
		2: "WATCH_EVENT_TYPE_PUT",
		3: "WATCH_EVENT_TYPE_DELETE",
		4: "WATCH_EVENT_TYPE_HEARTBEAT",
	}
	WatchEventType_value = map[string]int32{
		"WATCH_EVENT_TYPE_UNSPECIFIED": 0,
		"WATCH_EVENT_TYPE_SNAPSHOT":    1,
		"WATCH_EVENT_TYPE_PUT":         2,
		"WATCH_EVENT_TYPE_DELETE":      3,
		"WATCH_EVENT_TYPE_HEARTBEAT":   4,
	}
)

func (x WatchEventType) Enum() *WatchEventType {
	p := new(WatchEventType)
	*p = x
	return p
}

func (x WatchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_config_v1_config_proto_enumTypes[1].Descriptor()
}

func (WatchEventType) Type() protoreflect.EnumType {
	return &file_api_config_v1_config_proto_enumTypes[1]
}

func (x WatchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEventType.Descriptor instead.
func (WatchEventType) EnumDescriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{1}
}

// 配置项(键 + 当前值 + 元数据)
type ConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Format        ConfigFormat           `protobuf:"varint,5,opt,name=format,proto3,enum=config.v1.ConfigFormat" json:"format,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"` // ListKeys 中为空(仅元数据);is_secret 时脱敏
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	IsSecret      bool                   `protobuf:"varint,8,opt,name=is_secret,json=isSecret,proto3" json:"is_secret,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEntry) Reset() {
	*x = ConfigEntry{}
	mi := &file_api_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEntry) ProtoMessage() {}

func (x *ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEntry.ProtoReflect.Descriptor instead.
func (*ConfigEntry) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigEntry) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigEntry) GetFormat() ConfigFormat {
	if x != nil {
		return x.Format
	}
	return ConfigFormat_CONFIG_FORMAT_UNSPECIFIED
}

func (x *ConfigEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigEntry) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigEntry) GetIsSecret() bool {
	if x != nil {
		return x.IsSecret
	}
	return false
}

func (x *ConfigEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigEntry) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ConfigEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfigEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 历史版本记录
type ConfigRevision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EntryId       int64                  `protobuf:"varint,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Format        ConfigFormat           `protobuf:"varint,4,opt,name=format,proto3,enum=config.v1.ConfigFormat" json:"format,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Author        string                 `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRevision) Reset() {
	*x = ConfigRevision{}
	mi := &file_api_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRevision) ProtoMessage() {}

func (x *ConfigRevision) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRevision.ProtoReflect.Descriptor instead.
func (*ConfigRevision) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigRevision) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigRevision) GetEntryId() int64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *ConfigRevision) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigRevision) GetFormat() ConfigFormat {
	if x != nil {
		return x.Format
	}
	return ConfigFormat_CONFIG_FORMAT_UNSPECIFIED
}

func (x *ConfigRevision) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigRevision) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ConfigRevision) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ConfigRevision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// namespace 概览:该 namespace 下已有配置的环境与 key 总数
type NamespaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environments  []string               `protobuf:"bytes,2,rep,name=environments,proto3" json:"environments,omitempty"`          // 该 namespace 下确实存在配置的环境,按名排序
	KeyCount      int32                  `protobuf:"varint,3,opt,name=key_count,json=keyCount,proto3" json:"key_count,omitempty"` // 所有环境合计的 key 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceInfo) Reset() {
	*x = NamespaceInfo{}
	mi := &file_api_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceInfo) ProtoMessage() {}

func (x *NamespaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceInfo.ProtoReflect.Descriptor instead.
func (*NamespaceInfo) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *NamespaceInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespaceInfo) GetEnvironments() []string {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *NamespaceInfo) GetKeyCount() int32 {
	if x != nil {
		return x.KeyCount
	}
	return 0
}

type ListNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{3}
}

type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*NamespaceInfo       `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"` // 按 namespace 名排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *ListNamespacesResponse) GetNamespaces() []*NamespaceInfo {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	KeyPrefix     string                 `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"` // 可选:按 key 前缀过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *ListKeysRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListKeysRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ListKeysRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

type ListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ConfigEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *ListKeysResponse) GetEntries() []*ConfigEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *GetKeyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *GetKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *ConfigEntry           `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *GetKeyResponse) GetEntry() *ConfigEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type PutKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Format        ConfigFormat           `protobuf:"varint,4,opt,name=format,proto3,enum=config.v1.ConfigFormat" json:"format,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"` // 变更备注
	IsSecret      bool                   `protobuf:"varint,7,opt,name=is_secret,json=isSecret,proto3" json:"is_secret,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutKeyRequest) Reset() {
	*x = PutKeyRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutKeyRequest) ProtoMessage() {}

func (x *PutKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutKeyRequest.ProtoReflect.Descriptor instead.
func (*PutKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *PutKeyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *PutKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutKeyRequest) GetFormat() ConfigFormat {
	if x != nil {
		return x.Format
	}
	return ConfigFormat_CONFIG_FORMAT_UNSPECIFIED
}

func (x *PutKeyRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutKeyRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PutKeyRequest) GetIsSecret() bool {
	if x != nil {
		return x.IsSecret
	}
	return false
}

func (x *PutKeyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PutKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *ConfigEntry           `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"` // 更新后的条目(含新版本号)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutKeyResponse) Reset() {
	*x = PutKeyResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutKeyResponse) ProtoMessage() {}

func (x *PutKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutKeyResponse.ProtoReflect.Descriptor instead.
func (*PutKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{10}
}

func (x *PutKeyResponse) GetEntry() *ConfigEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type DeleteKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteKeyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *DeleteKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteKeyResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListRevisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRevisionsRequest) Reset() {
	*x = ListRevisionsRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevisionsRequest) ProtoMessage() {}

func (x *ListRevisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevisionsRequest.ProtoReflect.Descriptor instead.
func (*ListRevisionsRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{13}
}

func (x *ListRevisionsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListRevisionsRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ListRevisionsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListRevisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*ConfigRevision      `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRevisionsResponse) Reset() {
	*x = ListRevisionsResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevisionsResponse) ProtoMessage() {}

func (x *ListRevisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevisionsResponse.ProtoReflect.Descriptor instead.
func (*ListRevisionsResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{14}
}

func (x *ListRevisionsResponse) GetRevisions() []*ConfigRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type GetRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevisionRequest) Reset() {
	*x = GetRevisionRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevisionRequest) ProtoMessage() {}

func (x *GetRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetRevisionRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{15}
}

func (x *GetRevisionRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRevisionRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *GetRevisionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRevisionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *ConfigRevision        `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevisionResponse) Reset() {
	*x = GetRevisionResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevisionResponse) ProtoMessage() {}

func (x *GetRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevisionResponse.ProtoReflect.Descriptor instead.
func (*GetRevisionResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{16}
}

func (x *GetRevisionResponse) GetRevision() *ConfigRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // 目标回滚版本
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{17}
}

func (x *RollbackRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RollbackRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RollbackRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RollbackRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RollbackRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *ConfigEntry           `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{18}
}

func (x *RollbackResponse) GetEntry() *ConfigEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type WatchKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Keys          []string               `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"` // 可选:留空表示订阅该 namespace+environment 下全部 key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchKeysRequest) Reset() {
	*x = WatchKeysRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchKeysRequest) ProtoMessage() {}

func (x *WatchKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchKeysRequest.ProtoReflect.Descriptor instead.
func (*WatchKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{19}
}

func (x *WatchKeysRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchKeysRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *WatchKeysRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type WatchKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WatchEventType         `protobuf:"varint,1,opt,name=type,proto3,enum=config.v1.WatchEventType" json:"type,omitempty"`
	Entry         *ConfigEntry           `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"` // HEARTBEAT 时为空;脱敏规则与 GetKey 一致
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchKeysResponse) Reset() {
	*x = WatchKeysResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchKeysResponse) ProtoMessage() {}

func (x *WatchKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchKeysResponse.ProtoReflect.Descriptor instead.
func (*WatchKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{20}
}

func (x *WatchKeysResponse) GetType() WatchEventType {
	if x != nil {
		return x.Type
	}
	return WatchEventType_WATCH_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchKeysResponse) GetEntry() *ConfigEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_api_config_v1_config_proto protoreflect.FileDescriptor

const file_api_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/config/v1/config.proto\x12\tconfig.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#third_party/validate/validate.proto\"\xa4\x03\n" +
	"\vConfigEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12/\n" +
	"\x06format\x18\x05 \x01(\x0e2\x17.config.v1.ConfigFormatR\x06format\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x12\x1b\n" +
	"\tis_secret\x18\b \x01(\bR\bisSecret\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x89\x02\n" +
	"\x0eConfigRevision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\x03R\aentryId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12/\n" +
	"\x06format\x18\x04 \x01(\x0e2\x17.config.v1.ConfigFormatR\x06format\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"n\n" +
	"\rNamespaceInfo\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\"\n" +
	"\fenvironments\x18\x02 \x03(\tR\fenvironments\x12\x1b\n" +
	"\tkey_count\x18\x03 \x01(\x05R\bkeyCount\"\x17\n" +
	"\x15ListNamespacesRequest\"R\n" +
	"\x16ListNamespacesResponse\x128\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x18.config.v1.NamespaceInfoR\n" +
	"namespaces\"\x80\x01\n" +
	"\x0fListKeysRequest\x12$\n" +
	"\tnamespace\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tnamespace\x12(\n" +
	"\venvironment\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\venvironment\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x03 \x01(\tR\tkeyPrefix\"D\n" +
	"\x10ListKeysResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.config.v1.ConfigEntryR\aentries\"y\n" +
	"\rGetKeyRequest\x12$\n" +
	"\tnamespace\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tnamespace\x12(\n" +
	"\venvironment\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\venvironment\x12\x18\n" +
	"\x03key\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03key\">\n" +
	"\x0eGetKeyResponse\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.config.v1.ConfigEntryR\x05entry\"\xa3\x02\n" +
	"\rPutKeyRequest\x12$\n" +
	"\tnamespace\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tnamespace\x12(\n" +
	"\venvironment\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\venvironment\x12\x18\n" +
	"\x03key\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03key\x129\n" +
	"\x06format\x18\x04 \x01(\x0e2\x17.config.v1.ConfigFormatB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06format\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x1b\n" +
	"\tis_secret\x18\a \x01(\bR\bisSecret\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\">\n" +
	"\x0ePutKeyResponse\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.config.v1.ConfigEntryR\x05entry\"|\n" +
	"\x10DeleteKeyRequest\x12$\n" +
	"\tnamespace\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tnamespace\x12(\n" +
	"\venvironment\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\venvironment\x12\x18\n" +
	"\x03key\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03key\"-\n" +
	"\x11DeleteKeyResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x80\x01\n" +
	"\x14ListRevisionsRequest\x12$\n" +
	"\tnamespace\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tnamespace\x12(\n" +
	"\venvironment\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\venvironment\x12\x18\n" +
	"\x03key\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03key\"P\n" +
	"\x15ListRevisionsResponse\x127\n" +
	"\trevisions\x18\x01 \x03(\v2\x19.config.v1.ConfigRevisionR\trevisions\"\xa1\x01\n" +
	"\x12GetRevisionRequest\x12$\n" +
	"\tnamespace\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tnamespace\x12(\n" +
	"\venvironment\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\venvironment\x12\x18\n" +
	"\x03key\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03key\x12!\n" +
	"\aversion\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\aversion\"L\n" +
	"\x13GetRevisionResponse\x125\n" +
	"\brevision\x18\x01 \x01(\v2\x19.config.v1.ConfigRevisionR\brevision\"\xb8\x01\n" +
	"\x0fRollbackRequest\x12$\n" +
	"\tnamespace\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tnamespace\x12(\n" +
	"\venvironment\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\venvironment\x12\x18\n" +
	"\x03key\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03key\x12!\n" +
	"\aversion\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\aversion\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\"@\n" +
	"\x10RollbackResponse\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.config.v1.ConfigEntryR\x05entry\"v\n" +
	"\x10WatchKeysRequest\x12$\n" +
	"\tnamespace\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tnamespace\x12(\n" +
	"\venvironment\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\venvironment\x12\x12\n" +
	"\x04keys\x18\x03 \x03(\tR\x04keys\"p\n" +
	"\x11WatchKeysResponse\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.config.v1.WatchEventTypeR\x04type\x12,\n" +
	"\x05entry\x18\x02 \x01(\v2\x16.config.v1.ConfigEntryR\x05entry*\x92\x01\n" +
	"\fConfigFormat\x12\x1d\n" +
	"\x19CONFIG_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONFIG_FORMAT_YAML\x10\x01\x12\x16\n" +
	"\x12CONFIG_FORMAT_TOML\x10\x02\x12\x16\n" +
	"\x12CONFIG_FORMAT_JSON\x10\x03\x12\x1b\n" +
	"\x17CONFIG_FORMAT_PLAINTEXT\x10\x04*\xa8\x01\n" +
	"\x0eWatchEventType\x12 \n" +
	"\x1cWATCH_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WATCH_EVENT_TYPE_SNAPSHOT\x10\x01\x12\x18\n" +
	"\x14WATCH_EVENT_TYPE_PUT\x10\x02\x12\x1b\n" +
	"\x17WATCH_EVENT_TYPE_DELETE\x10\x03\x12\x1e\n" +
	"\x1aWATCH_EVENT_TYPE_HEARTBEAT\x10\x042\xb4\x05\n" +
	"\rConfigService\x12W\n" +
	"\x0eListNamespaces\x12 .config.v1.ListNamespacesRequest\x1a!.config.v1.ListNamespacesResponse\"\x00\x12E\n" +
	"\bListKeys\x12\x1a.config.v1.ListKeysRequest\x1a\x1b.config.v1.ListKeysResponse\"\x00\x12?\n" +
	"\x06GetKey\x12\x18.config.v1.GetKeyRequest\x1a\x19.config.v1.GetKeyResponse\"\x00\x12?\n" +
	"\x06PutKey\x12\x18.config.v1.PutKeyRequest\x1a\x19.config.v1.PutKeyResponse\"\x00\x12H\n" +
	"\tDeleteKey\x12\x1b.config.v1.DeleteKeyRequest\x1a\x1c.config.v1.DeleteKeyResponse\"\x00\x12T\n" +
	"\rListRevisions\x12\x1f.config.v1.ListRevisionsRequest\x1a .config.v1.ListRevisionsResponse\"\x00\x12N\n" +
	"\vGetRevision\x12\x1d.config.v1.GetRevisionRequest\x1a\x1e.config.v1.GetRevisionResponse\"\x00\x12E\n" +
	"\bRollback\x12\x1a.config.v1.RollbackRequest\x1a\x1b.config.v1.RollbackResponse\"\x00\x12J\n" +
	"\tWatchKeys\x12\x1b.config.v1.WatchKeysRequest\x1a\x1c.config.v1.WatchKeysResponse\"\x000\x01B\xa0\x01\n" +
	"\rcom.config.v1B\vConfigProtoP\x01Z=github.com/lens077/go-connect-template/api/config/v1;configv1\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1b\x06proto3"

var (
	file_api_config_v1_config_proto_rawDescOnce sync.Once
	file_api_config_v1_config_proto_rawDescData []byte
)

func file_api_config_v1_config_proto_rawDescGZIP() []byte {
	file_api_config_v1_config_proto_rawDescOnce.Do(func() {
		file_api_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_config_v1_config_proto_rawDesc), len(file_api_config_v1_config_proto_rawDesc)))
	})
	return file_api_config_v1_config_proto_rawDescData
}

var file_api_config_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_config_v1_config_proto_goTypes = []any{
	(ConfigFormat)(0),              // 0: config.v1.ConfigFormat
	(WatchEventType)(0),            // 1: config.v1.WatchEventType
	(*ConfigEntry)(nil),            // 2: config.v1.ConfigEntry
	(*ConfigRevision)(nil),         // 3: config.v1.ConfigRevision
	(*NamespaceInfo)(nil),          // 4: config.v1.NamespaceInfo
	(*ListNamespacesRequest)(nil),  // 5: config.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil), // 6: config.v1.ListNamespacesResponse
	(*ListKeysRequest)(nil),        // 7: config.v1.ListKeysRequest
	(*ListKeysResponse)(nil),       // 8: config.v1.ListKeysResponse
	(*GetKeyRequest)(nil),          // 9: config.v1.GetKeyRequest
	(*GetKeyResponse)(nil),         // 10: config.v1.GetKeyResponse
	(*PutKeyRequest)(nil),          // 11: config.v1.PutKeyRequest
	(*PutKeyResponse)(nil),         // 12: config.v1.PutKeyResponse
	(*DeleteKeyRequest)(nil),       // 13: config.v1.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),      // 14: config.v1.DeleteKeyResponse
	(*ListRevisionsRequest)(nil),   // 15: config.v1.ListRevisionsRequest
	(*ListRevisionsResponse)(nil),  // 16: config.v1.ListRevisionsResponse
	(*GetRevisionRequest)(nil),     // 17: config.v1.GetRevisionRequest
	(*GetRevisionResponse)(nil),    // 18: config.v1.GetRevisionResponse
	(*RollbackRequest)(nil),        // 19: config.v1.RollbackRequest
	(*RollbackResponse)(nil),       // 20: config.v1.RollbackResponse
	(*WatchKeysRequest)(nil),       // 21: config.v1.WatchKeysRequest
	(*WatchKeysResponse)(nil),      // 22: config.v1.WatchKeysResponse
	(*timestamppb.Timestamp)(nil),  // 23: google.protobuf.Timestamp
}
var file_api_config_v1_config_proto_depIdxs = []int32{
	0,  // 0: config.v1.ConfigEntry.format:type_name -> config.v1.ConfigFormat
	23, // 1: config.v1.ConfigEntry.created_at:type_name -> google.protobuf.Timestamp
	23, // 2: config.v1.ConfigEntry.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: config.v1.ConfigRevision.format:type_name -> config.v1.ConfigFormat
	23, // 4: config.v1.ConfigRevision.created_at:type_name -> google.protobuf.Timestamp
	4,  // 5: config.v1.ListNamespacesResponse.namespaces:type_name -> config.v1.NamespaceInfo
	2,  // 6: config.v1.ListKeysResponse.entries:type_name -> config.v1.ConfigEntry
	2,  // 7: config.v1.GetKeyResponse.entry:type_name -> config.v1.ConfigEntry
	0,  // 8: config.v1.PutKeyRequest.format:type_name -> config.v1.ConfigFormat
	2,  // 9: config.v1.PutKeyResponse.entry:type_name -> config.v1.ConfigEntry
	3,  // 10: config.v1.ListRevisionsResponse.revisions:type_name -> config.v1.ConfigRevision
	3,  // 11: config.v1.GetRevisionResponse.revision:type_name -> config.v1.ConfigRevision
	2,  // 12: config.v1.RollbackResponse.entry:type_name -> config.v1.ConfigEntry
	1,  // 13: config.v1.WatchKeysResponse.type:type_name -> config.v1.WatchEventType
	2,  // 14: config.v1.WatchKeysResponse.entry:type_name -> config.v1.ConfigEntry
	5,  // 15: config.v1.ConfigService.ListNamespaces:input_type -> config.v1.ListNamespacesRequest
	7,  // 16: config.v1.ConfigService.ListKeys:input_type -> config.v1.ListKeysRequest
	9,  // 17: config.v1.ConfigService.GetKey:input_type -> config.v1.GetKeyRequest
	11, // 18: config.v1.ConfigService.PutKey:input_type -> config.v1.PutKeyRequest
	13, // 19: config.v1.ConfigService.DeleteKey:input_type -> config.v1.DeleteKeyRequest
	15, // 20: config.v1.ConfigService.ListRevisions:input_type -> config.v1.ListRevisionsRequest
	17, // 21: config.v1.ConfigService.GetRevision:input_type -> config.v1.GetRevisionRequest
	19, // 22: config.v1.ConfigService.Rollback:input_type -> config.v1.RollbackRequest
	21, // 23: config.v1.ConfigService.WatchKeys:input_type -> config.v1.WatchKeysRequest
	6,  // 24: config.v1.ConfigService.ListNamespaces:output_type -> config.v1.ListNamespacesResponse
	8,  // 25: config.v1.ConfigService.ListKeys:output_type -> config.v1.ListKeysResponse
	10, // 26: config.v1.ConfigService.GetKey:output_type -> config.v1.GetKeyResponse
	12, // 27: config.v1.ConfigService.PutKey:output_type -> config.v1.PutKeyResponse
	14, // 28: config.v1.ConfigService.DeleteKey:output_type -> config.v1.DeleteKeyResponse
	16, // 29: config.v1.ConfigService.ListRevisions:output_type -> config.v1.ListRevisionsResponse
	18, // 30: config.v1.ConfigService.GetRevision:output_type -> config.v1.GetRevisionResponse
	20, // 31: config.v1.ConfigService.Rollback:output_type -> config.v1.RollbackResponse
	22, // 32: config.v1.ConfigService.WatchKeys:output_type -> config.v1.WatchKeysResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_config_v1_config_proto_init() }
func file_api_config_v1_config_proto_init() {
	if File_api_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_config_v1_config_proto_rawDesc), len(file_api_config_v1_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_config_v1_config_proto_goTypes,
		DependencyIndexes: file_api_config_v1_config_proto_depIdxs,
		EnumInfos:         file_api_config_v1_config_proto_enumTypes,
		MessageInfos:      file_api_config_v1_config_proto_msgTypes,
	}.Build()
	File_api_config_v1_config_proto = out.File
	file_api_config_v1_config_proto_goTypes = nil
	file_api_config_v1_config_proto_depIdxs = nil
}
