### healthz
POST http://{{host}}:{{port}}/healthz
Content-Type: application/json

### k8s svc healthz
POST http://{{k8s_host}}:{{port}}/healthz
Content-Type: application/json

### 网关
POST http://{{k8s_gateway_host}}:{{k8s_gateway_port}}/search/search.v1.SearchService/Search
Content-Type: application/json

{"index": "ecommerce_products_spus", "name": "iphone"}

### k8s网关
POST http://{{k8s_gateway_host}}:{{k8s_gateway_port}}/search/search.v1.SearchService/Search
Content-Type: application/json

{"index": "ecommerce_products_spus", "name": "iphone"}

### 直连后端
POST http://{{host}}:{{port}}/search.v1.SearchService/Search
Content-Type: application/json

{"index": "ecommerce_products_spus", "name": "iphone"}
